version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - "8000:8000"

  init-ddb:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Esperando a DynamoDB..."
        sleep 5
        echo "Creando tabla si no existe..."
        aws dynamodb create-table \
          --endpoint-url http://dynamodb:8000 \
          --table-name LinklyTable \
          --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
          --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST || true
        echo "Tabla verificada ✅"
    environment:
      AWS_REGION: "us-east-1"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"

  ms-admin:
    build: .
    depends_on:
      dynamodb:
        condition: service_started
      init-ddb:
        condition: service_completed_successfully
    environment:
      PORT: 8080
      AWS_REGION: us-east-1
      DDB_TABLE: LinklyTable
      DDB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080
