AWSTemplateFormatVersion: '2010-09-09'
Description: Core infraestructura para Linkly (Producción)

Parameters:
  Environment:
    Type: String
    Default: production
  VpcId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  RootDomain:
    Type: String
  AppDomain:
    Type: String
  AdminDomain:
    Type: String

Resources:
  # Security Group para el ALB
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG para ALB ${Environment}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub linkly-${Environment}-alb-sg

  # Security Group para los servicios ECS
  ServicesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG para ECS ${Environment}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub linkly-${Environment}-services-sg

  # ALB principal
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub linkly-${Environment}-alb
      Scheme: internet-facing
      SecurityGroups: [!Ref AlbSecurityGroup]
      Subnets: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub linkly-${Environment}-alb

  # Listener HTTP
  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: text/plain
            MessageBody: "Linkly ALB (Producción)"
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  ALBDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub linkly-${Environment}-ALBDnsName

  ServicesSg:
    Value: !Ref ServicesSecurityGroup
    Export:
      Name: !Sub linkly-${Environment}-ServicesSg
