AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront para Linkly (solo production) usando certs existentes

Parameters:
  Environment:
    Type: String
    AllowedValues: [production]
    Default: production
  RootDomain:
    Type: String
    Default: linkly.space
  AppDomain:
    Type: String
    Default: app.linkly.space
  CertificateArnRoot:
    Type: String
    Description: ACM ARN para linkly.space (en us-east-1)
  CertificateArnApp:
    Type: String
    Description: ACM ARN para app.linkly.space (en us-east-1)

Resources:
  CfApp:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: [!Ref AppDomain]
        Origins:
          - Id: origin-alb-app
            DomainName: !ImportValue linkly-production-ALBDnsName
            CustomOriginConfig: { OriginProtocolPolicy: http-only }
        DefaultCacheBehavior:
          TargetOriginId: origin-alb-app
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6   # CachingOptimized (AWS managed)
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # AllViewerExceptHostHeader
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArnApp
          SslSupportMethod: sni-only

  CfRoot:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: [!Ref RootDomain]
        Origins:
          - Id: origin-alb-root
            DomainName: !ImportValue linkly-production-ALBDnsName
            CustomOriginConfig: { OriginProtocolPolicy: http-only }
        DefaultCacheBehavior:
          TargetOriginId: origin-alb-root
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # AllViewer
          ForwardedValues:
            QueryString: true
            Headers:
              - CloudFront-Viewer-Country
              - CloudFront-Is-Mobile-Viewer
              - CloudFront-Viewer-Device-Type
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArnRoot
          SslSupportMethod: sni-only

Outputs:
  CloudFrontAppId:
    Value: !Ref CfApp
    Export: { Name: linkly-production-CloudFrontAppId }
  CloudFrontRootId:
    Value: !Ref CfRoot
    Export: { Name: linkly-production-CloudFrontRootId }
