name: CD — Producción AWS ECS

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ROOT_DOMAIN: linkly.space
  APP_DOMAIN: app.linkly.space
  ADMIN_DOMAIN: admin.linkly.space

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Core (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-core-prod.yaml \
            --stack-name linkly-production-core \
            --parameter-overrides \
              Environment=production \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetIds="${{ secrets.SUBNET_IDS }}" \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: Deploy Data (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-data-prod.yaml \
            --stack-name linkly-production-data \
            --parameter-overrides Environment=production \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: Deploy ECS Services (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-ecs-services-prod.yaml \
            --stack-name linkly-production-ecs \
            --parameter-overrides \
              Environment=production \
              LabRoleArn=${{ secrets.LAB_ROLE_ARN }} \
              DockerHubUser=${{ secrets.DOCKERHUB_USERNAME }} \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes
