name: Infra — CloudFormation (staging & prod)

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ROOT_DOMAIN: linkly.space
  APP_DOMAIN: app.linkly.space
  ADMIN_DOMAIN: admin.linkly.space

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      # ---------- STAGING ----------
      - name: Core (staging)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-core.yaml \
            --stack-name linkly-staging-core \
            --parameter-overrides \
              Environment=staging \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetIds="${{ secrets.SUBNET_IDS }}" \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: Data (staging)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-data.yaml \
            --stack-name linkly-staging-data \
            --parameter-overrides Environment=staging \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: ECS Services (staging)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-ecs-services.yaml \
            --stack-name linkly-staging-ecs \
            --parameter-overrides \
              Environment=staging \
              LabRoleArn=${{ secrets.LAB_ROLE_ARN }} \
              DockerHubUser=${{ secrets.DOCKERHUB_USERNAME }} \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      # ---------- PRODUCTION ----------
      - name: Core (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-core.yaml \
            --stack-name linkly-production-core \
            --parameter-overrides \
              Environment=production \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetIds="${{ secrets.SUBNET_IDS }}" \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: Data (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-data.yaml \
            --stack-name linkly-production-data \
            --parameter-overrides Environment=production \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: ECS Services (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-ecs-services.yaml \
            --stack-name linkly-production-ecs \
            --parameter-overrides \
              Environment=production \
              LabRoleArn=${{ secrets.LAB_ROLE_ARN }} \
              DockerHubUser=${{ secrets.DOCKERHUB_USERNAME }} \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              AdminDomain=${{ env.ADMIN_DOMAIN }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes

      - name: CloudFront (prod)
        run: |
          aws cloudformation deploy \
            --template-file infra/linkly-cloudfront-prod.yaml \
            --stack-name linkly-production-cf \
            --parameter-overrides \
              Environment=production \
              RootDomain=${{ env.ROOT_DOMAIN }} \
              AppDomain=${{ env.APP_DOMAIN }} \
              CertificateArnRoot=${{ secrets.ACM_ARN_ROOT }} \
              CertificateArnApp=${{ secrets.ACM_ARN_APP }} \
            --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changes
