name: Monorepo CI (unit tests only)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Evita carreras si hay múltiples pushes a la misma rama/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # 1) Detectar qué carpetas cambiaron
  changed:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      ms_admin: ${{ steps.filter.outputs.ms_admin }}
      ms_redirect: ${{ steps.filter.outputs.ms_redirect }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          # Si cambias estos patrones, ajusta según tu estructura real
          filters: |
            frontend:
              - 'frontend/**'
            ms_admin:
              - 'ms-admin/**'
            ms_redirect:
              - 'ms-redirect/**'
            # Si quieres que cambios de infra/README NO disparen tests, no los listes aquí

  # 2) Tests Python - frontend
  test-frontend:
    name: frontend · pytest
    needs: changed
    if: needs.changed.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            frontend/requirements.txt
            frontend/pyproject.toml
            frontend/setup.cfg

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Asegura pytest si no está en requirements
          python -m pip install -U pytest

      - name: Run unit tests
        run: |
          pytest -q tests/test_app.py

  # 3) Tests Python - ms-admin
  test-ms-admin:
    name: ms-admin · pytest
    needs: changed
    if: needs.changed.outputs.ms_admin == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ms-admin
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            ms-admin/requirements.txt
            ms-admin/pyproject.toml
            ms-admin/setup.cfg

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -U pytest

      - name: Run unit tests
        run: |
          pytest -q tests/unit

  # 4) Tests Node - ms-redirect
  test-ms-redirect:
    name: ms-redirect · vitest
    needs: changed
    if: needs.changed.outputs.ms_redirect == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ms-redirect
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ms-redirect/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run unit tests (vitest)
        run: npm test --silent

  # 5) No-op amigable si nada cambió
  nothing-to-test:
    name: Nothing to test
    needs: changed
    if: needs.changed.outputs.frontend != 'true' &&
        needs.changed.outputs.ms_admin != 'true' &&
        needs.changed.outputs.ms_redirect != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changed projects. Skipping unit tests."
